var q18 = ["Canada", "America", "Germany", "France", "India"];
var iq18 = '["' + q18.join('","') + '"]';
console.log("original from");
console.log(iq18);
console.log("\n");
var arr2 = q18.sort();
var aor = '["' + arr2.join('","') + '"]';
console.log("alphabetical from");
console.log(aor);
console.log("\n");
console.log("original from");
console.log(iq18);
console.log("\n");
arr2 = arr2.reverse();
var ao = '["' + arr2.join('","') + '"]';
console.log("reverse alphabetical from");
console.log(ao);
console.log("\n");
console.log("original from");
console.log(iq18);
console.log("\n");
q18 = q18.reverse();
console.log("reverse from");
console.log('["' + q18.join('","') + '"]');
console.log("\n");
q18 = q18.reverse();
console.log("original from");
console.log('["' + q18.join('","') + '"]');
console.log("\n");
q18 = q18.sort();
console.log("alphabetical from");
console.log('["' + q18.join('","') + '"]');
console.log("\n");
q18 = q18.reverse();
console.log("reverse alphabetical from");
console.log('["' + q18.join('","') + '"]');
console.log("\n");
