var a = "rawalpindi";
var b = "islamabaad";
console.log(a == b);
console.log(a != b);
console.log(a == 'Rawalpindi');
console.log(a != 'Rawalpindi');
console.log(1 > 2);
console.log(1 < 2);
console.log(1 == 1);
console.log(2 != 2);
console.log(3 >= 3);
console.log(2 >= 323);
console.log(19 <= 20);
console.log(191 <= 20);
console.log(a != b && 2 > 1);
console.log(a == b && 2 <= 1);
console.log('Rawalpindi' != a || 1 >= 1);
console.log('Rawalpindi' != a || 0 >= 1);
var q24 = [1, 2, 4];
console.log(q24[2] == 4);
console.log(q24[1] == 34);
